"""fix

Revision ID: 37b62bde14bf
Revises: 43e4ae076d43
Create Date: 2022-08-10 12:29:14.972522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
import bot

revision = '37b62bde14bf'
down_revision = '43e4ae076d43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('upd_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('subs_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('posts',
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('upd_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', mysql.TEXT(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('pr_type', sa.Enum('NONE', 'CLICKS', 'PUBLICATIONS', name='prtype'), nullable=True),
    sa.Column('pub_price', sa.Integer(), nullable=False),
    sa.Column('url_price', sa.Integer(), nullable=False),
    sa.Column('subs_min', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('post_channels',
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('upd_date', sa.DateTime(), nullable=True),
    sa.Column('post', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['post'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post', 'channel')
    )
    op.create_table('urls',
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('upd_date', sa.DateTime(), nullable=True),
    sa.Column('url', bot.db.types.url.URLType(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('clicks_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('url'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls')
    op.drop_table('post_channels')
    op.drop_table('posts')
    op.drop_table('channels')
    # ### end Alembic commands ###
