"""FSM

Revision ID: 4089deba8fcc
Revises: 4d6e9bca4b81
Create Date: 2022-07-25 13:07:07.281544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4089deba8fcc'
down_revision = '4d6e9bca4b81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
