"""

Revision ID: e0cca1fdbba3
Revises: 37b62bde14bf
Create Date: 2022-08-16 20:22:46.737614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0cca1fdbba3'
down_revision = '37b62bde14bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### handlers auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'channels', ['id'])
    op.drop_column('post_channels', 'creation_date')
    op.drop_column('post_channels', 'upd_date')
    op.create_unique_constraint(None, 'posts', ['id'])
    op.alter_column('urls', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic handlers ###


def downgrade() -> None:
    # ### handlers auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'posts', type_='unique')
    op.add_column('post_channels', sa.Column('upd_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('post_channels', sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'channels', type_='unique')
    # ### end Alembic handlers ###
